groups:
- name: go-app
  rules:
  - alert: HighRequestLatency
    expr: http_request_duration_seconds_sum / http_request_duration_seconds_count > 0.5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "Request latency is above 0.5s (current value: {{ $value }}s)"

  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job) > 0.01
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate on {{ $labels.job }}"
      description: "Error rate is above 1% (current value: {{ $value }})"