apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia2lhbnlhcmkiLCJwYXNzd29yZCI6ImdocF9BQVRuR2pURlB3SzFsV3FVMHU1QWI1czAwYTJ0YksyRzJrVksiLCJhdXRoIjoiYTJsaGJubGhjbWs2WjJod1gwRkJWRzVIYWxSR1VIZExNV3hYY1ZVd2RUVkJZalZ6TURCaE1uUmlTekpITW10V1N3PT0ifX19
kind: Secret
metadata:
  name: github-registry-secret
type: kubernetes.io/dockerconfigjson
