global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-application'
    static_configs:
      - targets: ['app:8080']  # Using the service name from docker-compose

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']