global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - node-exporter:9100

  - job_name: 'app'
    static_configs:
      - targets: 
        - app:8080