apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  labels:
    app: postgres 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi