apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
        - name: {{.Values.appName}}
          image: ghcr.io/kianyari/k8s:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{.Values.appName}}
