apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

  DB_HOST: cGc=
  DB_PORT: NTQzMg==
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=

